# -*- coding: utf-8 -*-
"""14_poly 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k0Vdb8nchBgzNoswJKY6C8fMqbB0psqa
"""

import numpy as pd
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')

dataset = pd.read_csv('Ice_cream_selling_data.csv')

dataset

plt.scatter(dataset['Temperature (°C)'],dataset['Ice Cream Sales (units)'])
plt.xlabel('Temperature (°C)')
plt.ylabel('Ice Cream Sales (units)')

X = dataset.iloc[:,[0]].values

X

X.shape

y = dataset.iloc[:,1].values

y

# linear Regression

from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X,y)

model.score(X,y)

plt.scatter(dataset['Temperature (°C)'],dataset['Ice Cream Sales (units)'])
plt.plot(X,model.predict(X),color='red')
plt.xlabel('Temperature (°C)')
plt.ylabel('Ice Cream Sales (units)')
plt.show()

model.predict([[6.5]])

# polynomial Regresion

X

y

from sklearn .preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=7)

X_poly = poly.fit_transform(X)

X_poly

model2 = LinearRegression()

model2.fit(X_poly,y)

model2.score(X_poly,y)

plt.scatter(dataset['Temperature (°C)'],dataset['Ice Cream Sales (units)'])
plt.plot(X,model2.predict(X_poly),color='red')
plt.xlabel('Temperature (°C)')
plt.ylabel('Ice Cream Sales (units)')
plt.show()

poly.transform([[6.5]])

model2.predict(poly.transform([[6.5]]))

model2.predict(poly.transform([[4]]))

model2.predict(poly.transform([[7]]))

